backend:
  name: git-gateway
  branch: main

preview_styles:
  - "/src/styles/global.css"

media_folder: "src/assets/images" # Emplacement où les fichiers seront stockés dans le dépôt
public_folder: "src/assets/images" # L'attribut src pour les médias téléchargés

collections:
    - name: "Home"
      label: "Page d'accueil"
      files:
        - file: "src/content/home.md"
          label: "Page d'accueil"
          name: "home_list"
          fields:
            - { label: "Titre", name: "title", widget: "string" }
            - { label: "Image principale", name: "hero_image", widget: "image" }
            - { label : "Slug", name: "slug", widget: "string" }
            - label : "Hero section"
              name : "hero_section"
              widget : "object"
              fields :
                - { label: "Titre", name: "title", widget: "string" }
                - { label: "Texte", name: "text", widget: "text" }
            - label : "About section"
              name : "about_section"
              widget : "object"
              fields :
                - { label: "Titre", name: "title", widget: "string" }
                - { label: "Texte", name: "text", widget: "text" }
                - { label: "Image", name: "about_image", widget: "image" }
